name: Automated Data Collection

on:
  schedule:
    # Run every 6 hours at minute 0
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  collect-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r aqi_prediction_project/requirements.txt

    - name: Collect Karachi data (Karachi-only system)
      run: |
        cd aqi_prediction_project
        python collect_yearly_data.py

    - name: Commit and push data updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        if git diff --staged --quiet; then
          echo "No data changes to commit"
        else
          git commit -m "Automated data collection: $(date)"
          git push
        fi

    - name: Cleanup old cache files
      run: |
        # Remove old cache files to prevent disk space issues
        find . -name "*.cache" -type f -mtime +7 -delete 2>/dev/null || true
